# Generated by Django 3.1.3 on 2020-11-16 05:03

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(0, 'Untested'), (1, 'Tested'), (2, 'Validated')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='')),
                ('last_modified', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='VariableProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
                ('references', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('p', materials.models.MyArrayField(blank=True, null=True)),
                ('T', materials.models.MyArrayField(blank=True, null=True)),
                ('cp', materials.models.MyArrayField(blank=True, null=True)),
                ('h', materials.models.MyArrayField(blank=True, null=True)),
                ('ki', materials.models.MyArrayField(blank=True, null=True)),
                ('kj', materials.models.MyArrayField(blank=True, null=True)),
                ('kk', materials.models.MyArrayField(blank=True, null=True)),
                ('emissivity', materials.models.MyArrayField(blank=True, null=True)),
                ('absorptivity', materials.models.MyArrayField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialversion')),
            ],
        ),
        migrations.CreateModel(
            name='ConstProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
                ('last_modified', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialversion')),
            ],
        ),
    ]
