# Generated by Django 3.2.3 on 2021-06-08 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('units', '0001_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialversion',
            name='material_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialversion_material_expert', to='sources.person'),
        ),
        migrations.AddField(
            model_name='materialversion',
            name='material_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialversion_material_lead', to='sources.person'),
        ),
        migrations.AddField(
            model_name='materialversion',
            name='modeling_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialversion_modeling_expert', to='sources.person'),
        ),
        migrations.AddField(
            model_name='materialversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialversion',
            name='other_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialversion_other_contact', to='sources.person'),
        ),
        migrations.AddField(
            model_name='materialpropertyinstance',
            name='material_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialversion'),
        ),
        migrations.AddField(
            model_name='materialpropertyinstance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialpropertyinstance',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialproperty'),
        ),
        migrations.AddField(
            model_name='materialproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialproperty',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.combounit'),
        ),
        migrations.AddField(
            model_name='material',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constproperty',
            name='property_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialpropertyinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='materialversion',
            unique_together={('material', 'version')},
        ),
    ]
