# Generated by Django 3.2.3 on 2021-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproperty',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
