# Generated by Django 3.2.3 on 2021-05-29 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0001_initial'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMaterialProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0, verbose_name='Material state')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.combounit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='constproperty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='constproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='constproperty',
            name='state',
        ),
        migrations.RemoveField(
            model_name='constproperty',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='matrixproperty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='matrixproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='matrixproperty',
            name='software',
        ),
        migrations.RemoveField(
            model_name='matrixproperty',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='variableproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='variableproperty',
            name='software',
        ),
        migrations.RemoveField(
            model_name='variableproperty',
            name='state',
        ),
        migrations.RemoveField(
            model_name='variableproperty',
            name='unit',
        ),
        migrations.CreateModel(
            name='MaterialProperty',
            fields=[
                ('abstractmaterialproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.abstractmaterialproperty')),
            ],
            options={
                'verbose_name_plural': 'Material properties',
            },
            bases=('materials.abstractmaterialproperty',),
        ),
        migrations.AddField(
            model_name='constproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialproperty'),
        ),
        migrations.AddField(
            model_name='matrixproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialproperty'),
        ),
        migrations.AddField(
            model_name='variableproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialproperty'),
        ),
    ]
