# Generated by Django 3.1.3 on 2020-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_matrixproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
