# Generated by Django 3.1.3 on 2020-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialversion',
            name='rating',
        ),
        migrations.AddField(
            model_name='materialversion',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'Validated'), ('B', 'Limited Validation'), ('C', 'Low Confidence Tests'), ('D', 'Estimate Only'), ('F', 'Inconsistent')], max_length=1, null=True),
        ),
    ]
