# Generated by Django 3.1.3 on 2021-01-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_itarconstproperty_itarmaterial_itarmaterialversion_itarmatrixproperty_itarvariableproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itarmaterial',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itarmaterialversion',
            name='version',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materialversion',
            name='version',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
