# Generated by Django 3.1.3 on 2021-01-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20210111_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itarmaterialversion',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itarmatrixproperty',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itarvariableproperties',
            name='material',
        ),
        migrations.DeleteModel(
            name='ITARConstProperty',
        ),
        migrations.DeleteModel(
            name='ITARMaterial',
        ),
        migrations.DeleteModel(
            name='ITARMaterialVersion',
        ),
        migrations.DeleteModel(
            name='ITARMatrixProperty',
        ),
        migrations.DeleteModel(
            name='ITARVariableProperties',
        ),
    ]
