# Generated by Django 3.1.3 on 2021-01-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('materials', '0008_auto_20210111_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='constproperty',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.combounit'),
        ),
    ]
