# Generated by Django 3.1.3 on 2021-01-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_auto_20210113_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='date',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='reference',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialversion'),
        ),
    ]
