# Generated by Django 3.1.3 on 2021-01-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.CharField(default='F. Bar et al.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='doc_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='reftype',
            field=models.PositiveIntegerField(choices=[(0, 'Journal article'), (1, 'Unpublished report'), (2, 'Book'), (3, 'Test data'), (4, 'Sim data'), (5, 'Other')], default=0),
        ),
    ]
