# Generated by Django 3.1.3 on 2021-01-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_variableproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variableproperty',
            options={'verbose_name_plural': 'Var props'},
        ),
        migrations.RenameField(
            model_name='constproperty',
            old_name='material',
            new_name='material_version',
        ),
        migrations.RenameField(
            model_name='matrixproperty',
            old_name='material',
            new_name='material_version',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='material',
            new_name='material_version',
        ),
        migrations.RenameField(
            model_name='variableproperties',
            old_name='material',
            new_name='material_version',
        ),
        migrations.RenameField(
            model_name='variableproperty',
            old_name='material',
            new_name='material_version',
        ),
    ]
