# Generated by Django 3.1.3 on 2021-01-14 01:11

from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20210114_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableproperty',
            name='T',
            field=materials.models.MyArrayField(blank=True, null=True, verbose_name='Temperature [K]'),
        ),
        migrations.AlterField(
            model_name='variableproperty',
            name='p',
            field=materials.models.MyArrayField(blank=True, null=True, verbose_name='Pressure [Pa]'),
        ),
        migrations.AlterField(
            model_name='variableproperty',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0, verbose_name='Material state'),
        ),
    ]
