# Generated by Django 3.1.3 on 2021-01-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_auto_20210114_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableProperties',
        ),
    ]
