# Generated by Django 3.1.3 on 2021-01-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_delete_variableproperties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variableproperty',
            options={'verbose_name_plural': 'Variable properties'},
        ),
    ]
