# Generated by Django 3.1.3 on 2021-01-17 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0024_auto_20210115_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reftype',
            field=models.PositiveIntegerField(choices=[(0, 'Journal article'), (1, 'Unpublished report'), (2, 'Book'), (3, 'Test data'), (4, 'Sim data'), (5, 'Poster'), (6, 'Presentation'), (7, 'Other')], default=0),
        ),
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('code_name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=500)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialversion')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Download model',
            },
        ),
    ]
