# Generated by Django 3.1.3 on 2021-01-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_auto_20210122_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadmodel',
            old_name='matv',
            new_name='material_version',
        ),
    ]
