# Generated by Django 3.1.3 on 2021-01-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20210122_0605'),
        ('materials', '0028_auto_20210122_1748'),
    ]

    operations = [
    ]
