# Generated by Django 3.1.3 on 2021-01-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0029_merge_20210123_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadModel',
        ),
    ]
