# Generated by Django 3.1.3 on 2021-01-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_auto_20210123_0128'),
        ('materials', '0030_delete_downloadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='constproperty',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='matrixproperty',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='variableproperty',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
    ]
