# Generated by Django 3.1.3 on 2021-01-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_delete_softwarereference'),
        ('materials', '0031_auto_20210125_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='material_version',
        ),
        migrations.AddField(
            model_name='reference',
            name='materials',
            field=models.ManyToManyField(to='materials.Material'),
        ),
        migrations.AddField(
            model_name='reference',
            name='softwares',
            field=models.ManyToManyField(to='software.Software'),
        ),
    ]
