# Generated by Django 3.1.3 on 2021-01-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_auto_20210129_0025'),
        ('materials', '0032_auto_20210128_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='materials',
            field=models.ManyToManyField(blank=True, to='materials.Material'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='softwares',
            field=models.ManyToManyField(blank=True, to='software.Software'),
        ),
    ]
