# Generated by Django 3.1.3 on 2021-03-04 01:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0037_material_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialversion',
            name='version_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialversion',
            name='version',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
