# Generated by Django 3.1.3 on 2021-03-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0038_auto_20210304_0107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialversion',
            unique_together={('material', 'version')},
        ),
    ]
