# Generated by Django 3.1.3 on 2021-01-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('length_dim', models.IntegerField(default=0)),
                ('mass_dim', models.IntegerField(default=0)),
                ('time_dim', models.IntegerField(default=0)),
                ('current_dim', models.IntegerField(default=0)),
                ('temp_dim', models.IntegerField(default=0)),
                ('mole_dim', models.IntegerField(default=0)),
                ('luminous_dim', models.IntegerField(default=0)),
                ('coeff', models.FloatField(default=1, verbose_name='Coeff for SI equiv.')),
                ('temp_offset', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComboUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseUnitPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.combounit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.baseunit')),
            ],
        ),
    ]
