# Generated by Django 3.2.3 on 2021-05-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('length_dim', models.IntegerField(default=0)),
                ('mass_dim', models.IntegerField(default=0)),
                ('time_dim', models.IntegerField(default=0)),
                ('current_dim', models.IntegerField(default=0)),
                ('temp_dim', models.IntegerField(default=0)),
                ('mole_dim', models.IntegerField(default=0)),
                ('luminous_dim', models.IntegerField(default=0)),
                ('coeff', models.FloatField(default=1, verbose_name='Coeff for SI equiv.')),
                ('temp_offset', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseUnitPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('current_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_unit', to='units.baseunit')),
                ('length_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='length_unit', to='units.baseunit')),
                ('luminous_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luminous_unit', to='units.baseunit')),
                ('mass_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_unit', to='units.baseunit')),
                ('mole_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mole_unit', to='units.baseunit')),
                ('temp_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_unit', to='units.baseunit')),
                ('time_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_unit', to='units.baseunit')),
            ],
        ),
        migrations.CreateModel(
            name='ComboUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unitsystem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BaseUnitPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.combounit')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.baseunitprefix')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.baseunit')),
            ],
        ),
    ]
