# Generated by Django 3.1.3 on 2021-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combounit',
            name='alternate_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
