# Generated by Django 3.2.3 on 2021-05-28 23:12

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import materials.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITARConstProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'ITAR Constant properties',
            },
        ),
        migrations.CreateModel(
            name='ITARMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'ITAR Materials',
            },
        ),
        migrations.CreateModel(
            name='ITARMaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('version', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)])),
                ('version_value', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'Validated'), ('B', 'Limited Validation'), ('C', 'Low Confidence Tests'), ('D', 'Estimate Only'), ('F', 'Inconsistent')], max_length=1, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='')),
                ('published', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ITAR Material versions',
            },
        ),
        migrations.CreateModel(
            name='ITARMatrixProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(max_length=500)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
            ],
            options={
                'verbose_name_plural': 'ITAR Matrix properties',
            },
        ),
        migrations.CreateModel(
            name='ITARVariableProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0, verbose_name='Material state')),
                ('p', materials.models.MyArrayField(blank=True, null=True, verbose_name='Pressure [Pa]')),
                ('T', materials.models.MyArrayField(blank=True, null=True, verbose_name='Temperature [K]')),
                ('values', materials.models.MyArrayField(blank=True, null=True)),
                ('material_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ITAR Variable properties',
            },
        ),
    ]
