# Generated by Django 3.1.3 on 2021-01-11 21:26

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITARMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ITAR Materials',
            },
        ),
        migrations.CreateModel(
            name='ITARMaterialVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'Validated'), ('B', 'Limited Validation'), ('C', 'Low Confidence Tests'), ('D', 'Estimate Only'), ('F', 'Inconsistent')], max_length=1, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterial')),
            ],
            options={
                'verbose_name_plural': 'ITAR Material versions',
            },
        ),
        migrations.CreateModel(
            name='ITARVariableProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
                ('references', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('p', materials.models.MyArrayField(blank=True, null=True)),
                ('T', materials.models.MyArrayField(blank=True, null=True)),
                ('cp', materials.models.MyArrayField(blank=True, null=True)),
                ('h', materials.models.MyArrayField(blank=True, null=True)),
                ('ki', materials.models.MyArrayField(blank=True, null=True)),
                ('kj', materials.models.MyArrayField(blank=True, null=True)),
                ('kk', materials.models.MyArrayField(blank=True, null=True)),
                ('emissivity', materials.models.MyArrayField(blank=True, null=True)),
                ('absorptivity', materials.models.MyArrayField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion')),
            ],
            options={
                'verbose_name_plural': 'ITAR Variable properties',
            },
        ),
        migrations.CreateModel(
            name='ITARMatrixProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(max_length=500)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
                ('last_modified', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion')),
            ],
            options={
                'verbose_name_plural': 'ITAR Matrix properties',
            },
        ),
        migrations.CreateModel(
            name='ITARConstProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('state', models.PositiveIntegerField(choices=[(0, 'Virgin'), (1, 'Char'), (2, 'Pyrolysis')], default=0)),
                ('last_modified', models.DateField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion')),
            ],
            options={
                'verbose_name_plural': 'ITAR Constant properties',
            },
        ),
    ]
