# Generated by Django 3.2.3 on 2021-06-08 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('units', '0001_initial'),
        ('itarmaterials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itarmaterialversion',
            name='material_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itarmaterialversion_material_expert', to='sources.person'),
        ),
        migrations.AddField(
            model_name='itarmaterialversion',
            name='material_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itarmaterialversion_material_lead', to='sources.person'),
        ),
        migrations.AddField(
            model_name='itarmaterialversion',
            name='modeling_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itarmaterialversion_modeling_expert', to='sources.person'),
        ),
        migrations.AddField(
            model_name='itarmaterialversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itarmaterialversion',
            name='other_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itarmaterialversion_other_contact', to='sources.person'),
        ),
        migrations.AddField(
            model_name='itarmaterialpropertyinstance',
            name='material_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion'),
        ),
        migrations.AddField(
            model_name='itarmaterialpropertyinstance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itarmaterialpropertyinstance',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialproperty'),
        ),
        migrations.AddField(
            model_name='itarmaterialproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itarmaterialproperty',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.combounit'),
        ),
        migrations.AddField(
            model_name='itarmaterial',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itarconstproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itarconstproperty',
            name='property_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialpropertyinstance'),
        ),
    ]
