# Generated by Django 3.2.3 on 2021-05-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20210529_0605'),
        ('itarmaterials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITARMaterialProperty',
            fields=[
                ('abstractmaterialproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.abstractmaterialproperty')),
            ],
            options={
                'verbose_name_plural': 'ITAR Material properties',
            },
            bases=('materials.abstractmaterialproperty',),
        ),
        migrations.RemoveField(
            model_name='itarconstproperty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itarconstproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itarconstproperty',
            name='state',
        ),
        migrations.RemoveField(
            model_name='itarconstproperty',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='itarmatrixproperty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itarmatrixproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itarmatrixproperty',
            name='software',
        ),
        migrations.RemoveField(
            model_name='itarmatrixproperty',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='itarvariableproperty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itarvariableproperty',
            name='software',
        ),
        migrations.RemoveField(
            model_name='itarvariableproperty',
            name='state',
        ),
        migrations.RemoveField(
            model_name='itarvariableproperty',
            name='unit',
        ),
        migrations.AddField(
            model_name='itarconstproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialproperty'),
        ),
        migrations.AddField(
            model_name='itarmatrixproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialproperty'),
        ),
        migrations.AddField(
            model_name='itarvariableproperty',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialproperty'),
        ),
    ]
