# Generated by Django 3.2.3 on 2021-06-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
        ('itarmaterials', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itarmaterialpropertyinstance',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialproperty'),
        ),
    ]
