# Generated by Django 3.1.3 on 2021-01-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('itarmaterials', '0003_auto_20210113_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itarconstproperty',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.combounit'),
        ),
    ]
