# Generated by Django 3.2.3 on 2021-06-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0003_alter_itarmaterialpropertyinstance_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITARMaterialProperty',
        ),
    ]
