# Generated by Django 3.1.3 on 2021-01-13 07:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itarmaterials', '0004_auto_20210113_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITARReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itarmaterials.itarmaterialversion')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ITAR References',
            },
        ),
    ]
