# Generated by Django 3.1.3 on 2021-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0005_itarreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='itarreference',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
