# Generated by Django 3.1.3 on 2021-01-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0011_auto_20210114_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itarconstproperty',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itarmatrixproperty',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itarreference',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itarvariableproperty',
            name='material',
        ),
        migrations.AlterField(
            model_name='itarconstproperty',
            name='material_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion'),
        ),
        migrations.AlterField(
            model_name='itarmatrixproperty',
            name='material_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion'),
        ),
        migrations.AlterField(
            model_name='itarreference',
            name='material_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itarmaterials.itarmaterialversion'),
        ),
        migrations.AlterField(
            model_name='itarvariableproperty',
            name='material_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion'),
        ),
    ]
