# Generated by Django 3.1.3 on 2021-01-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0013_auto_20210115_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itarreference',
            name='reftype',
            field=models.PositiveIntegerField(choices=[(0, 'Journal article'), (1, 'Unpublished report'), (2, 'Book'), (3, 'Test data'), (4, 'Sim data'), (5, 'Poster'), (6, 'Presentation'), (7, 'Other')], default=0),
        ),
    ]
