# Generated by Django 3.1.3 on 2021-01-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0015_auto_20210122_0605'),
        ('itarmaterials', '0015_itarmatrixproperty_unit'),
    ]

    operations = [
    ]
