# Generated by Django 3.1.3 on 2021-01-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_auto_20210123_0128'),
        ('itarmaterials', '0016_merge_20210123_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='itarconstproperty',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='itarmatrixproperty',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
        migrations.AddField(
            model_name='itarvariableproperty',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.software'),
        ),
    ]
