# Generated by Django 3.1.3 on 2021-01-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0019_auto_20210129_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITARReference',
        ),
    ]
