# Generated by Django 3.1.3 on 2021-01-29 22:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0021_auto_20210129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itarmaterial',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
