# Generated by Django 3.1.3 on 2021-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0022_auto_20210129_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='itarmaterial',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
