# Generated by Django 3.1.3 on 2021-01-29 21:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('software', '0010_delete_tutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0034_delete_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('materials', models.ManyToManyField(blank=True, to='materials.Material')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('softwares', models.ManyToManyField(blank=True, to='software.Software')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('doc_num', models.CharField(blank=True, max_length=100, null=True)),
                ('reftype', models.PositiveIntegerField(choices=[(0, 'Journal article'), (1, 'Unpublished report'), (2, 'Book'), (3, 'Test data'), (4, 'Sim data'), (5, 'Poster'), (6, 'Presentation'), (7, 'Other')], default=0)),
                ('published', models.DateField(blank=True, null=True)),
                ('authors', models.CharField(max_length=50)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('materials', models.ManyToManyField(blank=True, to='materials.Material')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('softwares', models.ManyToManyField(blank=True, to='software.Software')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
