# Generated by Django 3.1.3 on 2021-01-22 05:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('contacts', '0002_auto_20210113_2223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0025_auto_20210117_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('how_to_get', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('how_to_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                #('point_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc', to='contacts.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('version', models.CharField(max_length=25, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('version_changes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                #('lead_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_developer', to='contacts.person')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                #('other_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_contact', to='contacts.person')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.software')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('link', models.URLField(null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.softwareversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('material_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialversion')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.softwareversion')),
            ],
            options={
                'verbose_name_plural': 'Export format',
            },
        ),
    ]
