# Generated by Django 3.1.3 on 2021-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='version',
            field=models.CharField(max_length=25),
        ),
    ]
