# Generated by Django 3.1.3 on 2021-01-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20210122_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
