# Generated by Django 3.1.3 on 2021-01-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_tutorial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
