# Generated by Django 3.1.3 on 2021-01-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_softwareversion_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
