# Generated by Django 3.1.3 on 2021-01-28 23:15

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0031_auto_20210125_2358'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0006_auto_20210123_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('doc_num', models.CharField(blank=True, max_length=100, null=True)),
                ('reftype', models.PositiveIntegerField(choices=[(0, 'Journal article'), (1, 'Unpublished report'), (2, 'Book'), (3, 'Test data'), (4, 'Sim data'), (5, 'Poster'), (6, 'Presentation'), (7, 'Other')], default=0)),
                ('authors', models.CharField(max_length=50)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('material_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.materialversion')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
