# Generated by Django 3.1.3 on 2021-01-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_softwarereference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftwareReference',
        ),
    ]
