# Generated by Django 3.1.3 on 2021-01-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_delete_softwarereference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='how_to_get',
        ),
        migrations.RemoveField(
            model_name='software',
            name='how_to_use',
        ),
    ]
