# Generated by Django 3.1.3 on 2021-03-04 01:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_auto_20210129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='version',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
