# Generated by Django 3.1.3 on 2021-03-04 22:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itarmaterials', '0024_auto_20210304_0107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0013_auto_20210304_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITARExportFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('material_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itarmaterials.itarmaterialversion')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.softwareversion')),
            ],
            options={
                'verbose_name_plural': 'ITAR export format',
            },
        ),
    ]
